Experiment 2: Data Cleaning and Data Imputation
Course: CSDL8013 Applied Data Science Lab
Dataset: Online Payments Fraud Detection
Objective: To apply data cleaning techniques including handling missing values,
encoding categorical variables, and feature scaling.

In [1]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler

In [2]:
df = pd.read_csv("data/online_fraud.csv")

print("Original Shape:", df.shape)

Original Shape: (6362620, 11)

In [3]:
df = df.sample(n=100000, random_state=42)
print("Sampled Shape:", df.shape)

Sampled Shape: (100000, 11)

In [4]:
df.isnull().sum()

step              0
type              0
amount            0
nameOrig          0
oldbalanceOrg     0
newbalanceOrig    0
nameDest          0
oldbalanceDest    0
newbalanceDest    0
isFraud           0
isFlaggedFraud    0
dtype: int64

In [5]:
df.loc[df.sample(frac=0.05).index, 'amount'] = np.nan
df.loc[df.sample(frac=0.05).index, 'oldbalanceOrg'] = np.nan

df.isnull().sum()

step                 0
type                 0
amount            5000
nameOrig             0
oldbalanceOrg     5000
newbalanceOrig       0
nameDest             0
oldbalanceDest       0
newbalanceDest       0
isFraud              0
isFlaggedFraud       0
dtype: int64

In [6]:
mean_imputer = SimpleImputer(strategy='mean')

df[['amount', 'oldbalanceOrg']] = mean_imputer.fit_transform(
    df[['amount', 'oldbalanceOrg']]
)

df.isnull().sum()

step              0
type              0
amount            0
nameOrig          0
oldbalanceOrg     0
newbalanceOrig    0
nameDest          0
oldbalanceDest    0
newbalanceDest    0
isFraud           0
isFlaggedFraud    0
dtype: int64

In [7]:
df.drop(['nameOrig', 'nameDest'], axis=1, inplace=True)

In [8]:
df = pd.get_dummies(df, columns=['type'], drop_first=True)

df.head()

,step,amount,oldbalanceOrg,newbalanceOrig,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud,type_CASH_OUT,type_DEBIT,type_PAYMENT,type_TRANSFER
3737323,278,330218.42,20866.00,351084.42,452419.57,122201.15,0,0,False,False,False,False
264914,15,11647.08,30370.00,18722.92,0.00,0.00,0,0,False,False,True,False
85647,10,152264.21,106589.00,258853.21,201303.01,49038.80,0,0,False,False,False,False
5899326,403,1551760.63,0.00,0.00,3198359.45,4750120.08,0,0,False,False,False,True
2544263,206,78172.30,2921331.58,2999503.88,415821.90,337649.60,0,0,False,False,False,False

In [9]:
df.dtypes

step                int64
amount            float64
oldbalanceOrg     float64
newbalanceOrig    float64
oldbalanceDest    float64
newbalanceDest    float64
isFraud             int64
isFlaggedFraud      int64
type_CASH_OUT        bool
type_DEBIT           bool
type_PAYMENT         bool
type_TRANSFER        bool
dtype: object

In [10]:
scaler = StandardScaler()

numerical_cols = ['step', 'amount', 'oldbalanceOrg',
                  'newbalanceOrig', 'oldbalanceDest',
                  'newbalanceDest']

df[numerical_cols] = scaler.fit_transform(df[numerical_cols])

df.head()

,step,amount,oldbalanceOrg,newbalanceOrig,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud,type_CASH_OUT,type_DEBIT,type_PAYMENT,type_TRANSFER
3737323,0.240608,0.271836,-0.287971,-0.172685,-0.202226,-0.318779,0,0,False,False,False,False
264914,-1.604774,-0.308138,-0.284614,-0.285857,-0.342598,-0.353941,0,0,False,False,True,False
85647,-1.639858,-0.052138,-0.257688,-0.204091,-0.280140,-0.339831,0,0,False,False,False,False
5899326,1.117691,2.495709,-0.295343,-0.292232,0.649758,1.012879,0,0,False,False,False,True
2544263,-0.264592,-0.187025,0.736663,0.729124,-0.213581,-0.256785,0,0,False,False,False,False

In [11]:
print("Final Shape:", df.shape)
print("Any Missing Values?", df.isnull().sum().sum())

Final Shape: (100000, 12)
Any Missing Values? 0